' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/02/17 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "climber plate and rod assbly", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.097019773125567366
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.048509886562783683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, 0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.014256822414994232, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.014256822414994232, 0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, 0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.021385233622491347, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.040424905468986402
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021385233622491347, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.056594867656580963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.085540934489965387, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.014256822414994232, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.048509886562783683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.040424905468986402
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017821028018742788, -0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.048509886562783683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.048509886562783683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.017821028018742788, -0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021385233622491347, -0.097019773125567366
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021385233622491347, -0.056594867656580963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.010692616811245673, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021385233622491347, -0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.021385233622491347, -0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0071284112074971161, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.021385233622491347, 0.11318973531316193
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.048509886562783683
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.014256822414994232, 0.10510475421936463
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, 0.080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.014256822414994232, 0.11318973531316193
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.021385233622491347, 0.10510475421936463
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.028513644829988465, 0.16169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.042770467244982693, 0.14552965968835105
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, 0.056594867656580963
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010692616811245673, 0.040424905468986402
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.021385233622491347, 0.064679848750378244
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, 0.040424905468986402
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, 0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.032339924375189122
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.024254943281391841
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035642056037485581, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, -0.040424905468986402
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0080849810937972805
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071284112074971161, -0.016169962187594561
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014256822414994232, 0.040424905468986402, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021385233622491347, 0.048509886562783683, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0.024254943281391841, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0.0080849810937972805, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.017821028018742788, 0.024254943281391841, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0.040424905468986402, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014256822414994232, 0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0071284112074971161, 0.0080849810937972805, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0080849810937972805, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, -0.040424905468986402, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, -0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, -0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071284112074971161, -0.0080849810937972805, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, -0.024254943281391841, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, -0.040424905468986402, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071284112074971161, -0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071284112074971161, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032077850433737023, -0.016169962187594561, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0, 0.5430748926133333, 0.4120256470311503, 0.45220865646138009
swApp.ExitApp
End Sub
