' ******************************************************************************
' swxJRNL.swj - journal recorded on 11/11/16 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "Assem1 - Copy", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.028482869174478492, 0.31280513059450166
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.014241434587239246, 0.11374732021618242
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035603586468098115, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.056873660108091209
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037915773405394142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.037915773405394142, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071207172936196229, 0.028436830054045605, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.028436830054045605, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.047394716756742679, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071207172936196229, 0.047394716756742679, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.037915773405394142, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.028436830054045605, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.066352603459439746, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.085310490162136821, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.056873660108091209, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.066352603459439746, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.047394716756742679, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.056873660108091209, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.028436830054045605, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.047394716756742679, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.047394716756742679, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071207172936196229, -0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.018957886702697071, 0.072999684754506688, 0.27839261811055849, 0.024132024418577203
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.23697358378371336, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.075831546810788283, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.047394716756742679, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.047394716756742679, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.056873660108091209, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.037915773405394142, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.028436830054045605, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0.047394716756742679, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.037915773405394142, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0094789433513485354, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.018957886702697071, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.10121760173342409, 0.1907993843358895, -0.1802083566170154
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.021362151880858868, -0.14218415027022804, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035603586468098115, -0.028436830054045605, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035603586468098115, -0.085310490162136821, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.066352603459439746, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.094789433513485358, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.085310490162136821, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.094789433513485358, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.18009992367562219, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.18957886702697072, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.085310490162136821, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.11384396786047546, 0.20787946068594465, -0.16613197931124901
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 33
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "rod", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.Extension.SelectByID2("", "FACE", -3.9147248287463299e-005, 0.27046895291061901, -0.0050798491604382434, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0, -0.072440131578947367, 0, True, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.0018520421570329404, 0.28617893514984871, -0.004730363606370247, False, 0, Nothing, 0)
Part.FeatEdit
Part.ClearSelection2 True
Part.SketchManager.InsertSketch True
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ActivateDoc2 "Assem1 - Copy", False, longstatus
Set Part = swApp.ActiveDoc
' MSGBOX
' Save changes to rod?

Set Part = Nothing
swApp.CloseDoc "rod"
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.017801793234049058, 0.16114203697292512
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010681075940429434, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010681075940429434, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071207172936196229, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071207172936196229, 0.037915773405394142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071207172936196229, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0071207172936196229, 0.056873660108091209
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.0035603586468098115, -0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035603586468098115, 0.13270520691887949
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.010681075940429434, 0.11374732021618242
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035603586468098115, 0.056873660108091209
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035603586468098115, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.037915773405394142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.018957886702697071
boolstatus = Part.Extension.SelectByID2("plate-1@Assem1 - Copy", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, -0.028436830054045605, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.028436830054045605, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037915773405394142, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.028436830054045605, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.047394716756742679, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.047394716756742679, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.028436830054045605, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.037915773405394142, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.018957886702697071, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.0094789433513485354, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035603586468098115, 0, 0.18826801949740002, 0.089129999532104875, -0.052443569143775903
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037915773405394142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.085310490162136821
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.0035603586468098115, 0.085310490162136821
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.047394716756742679
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.037915773405394142
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.028436830054045605
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.018957886702697071
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.0094789433513485354
Part.ClearSelection2 True
' MSGBOX
' Save changes to Assem1 - Copy?

Set Part = Nothing
swApp.CloseDoc "Assem1 - Copy"
swApp.ExitApp
End Sub
