' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/02/17 by USER
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = _
Application.SldWorks

swApp.ActivateDoc2 "climber black rod and plate assbly", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Part.ViewZoomtofit2
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.25105819392047124, 0.33801080640864711, 0.44382560170913621, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0.25871939500151298, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.0080849810937972805, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.040424905468986402, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014256822414994232, 0.12935969750075649, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0.016169962187594561, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0.0080849810937972805, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0.0080849810937972805, 0.25105819392047124, 0.35036863955991748, 0.43695865067815021
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("", "FACE", 0.25105819392064177, 0.33868283510093988, 0.44531455915208085, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.10336196250870817, -0.10510475421936463, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024949439226239906, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, -0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032077850433737023, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028513644829988465, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049898878452479811, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039206261641234141, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, -0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039206261641234141, -0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039206261641234141, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032077850433737023, -0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014256822414994232, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.032077850433737023, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05346308405622837, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.049898878452479811, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.049898878452479811, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.049898878452479811, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.035642056037485575, 0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.032077850433737023, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05346308405622837, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.060591495263725488, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0035642056037485581, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.014256822414994232, -0.16169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.2829743382829048, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.25871939500151298, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071284112074971161, -0.13744467859455375, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, -0.040424905468986402, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, -0.056594867656580963, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032077850433737023, -0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, -0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.032077850433737023, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, 0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, 0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0.040424905468986402, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.028513644829988465, 0.072764829844175524, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.039206261641234141, 0.10510475421936463, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.085540934489965387, 0.17786958406354017, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049898878452479811, 0.097019773125567366, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0.032339924375189122, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.064155700867474047, 0.064679848750378244, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.085540934489965387, 0.056594867656580963, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.099797756904959622, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.085540934489965387, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.09623355130121107, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.057027289659976929, -0.024254943281391841, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.024949439226239906, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.028513644829988465, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.010692616811245673, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.048509886562783683, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0.10510475421936463, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0.080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.017821028018742788, 0.097019773125567366, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024949439226239906, 0.072764829844175524, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.046334672848731252, 0.080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.092669345697462505, 0.056594867656580963, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.049898878452479811, 0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, 0.016169962187594561, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0071284112074971161, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0035642056037485581, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.010692616811245673, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.021385233622491347, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.024949439226239906, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.046334672848731252, -0.0080849810937972805, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.014256822414994232, 0, 0.040600430335871351, 0.33405698257527661, 0.44534652647845974
swApp.ExitApp
End Sub
